/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SQL_SERVER;

import java.sql.*;
import javax.swing.*;

public class CRUD_Calitos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CRUD_Calitos.class.getName());
    public int addedit;
    public CRUD_Calitos(){
        initComponents();
        addedit=1;
        
    }
    public void habilitar(boolean ha){
        txtnombre.setEnabled(ha);
        txtapellido.setEnabled(ha);
        txtusuario.setEnabled(ha);
        rbNo.setEnabled(ha);
        rbSi.setEnabled(ha);
        btnguardar.setEnabled(ha);
        btnborrar.setEnabled(ha);
        btncambiar_contra.setEnabled(ha);
    }
    public void limpiar(){
        txtnombre.setText("");
        txtapellido.setText("");
        txtusuario.setText("");
        txtPass.setText("");
        txtConfirPass.setText("");
        rbSi.setSelected(false);
        rbNo.setSelected(false);
        
    }
    public void convertirMayuscula(JTextField txt){
        txt.setText(txt.getText().trim().toUpperCase());
    }
    public void insertar(){
        String sql="INSERT INTO usuarios (nombre,apellido,usuario,pass,confirpass,estatus,borrado,borrado_fecha,adiciono) VALUES (?,?,?,?,?,?,?,?,?)";
        try(Connection conn=conexion.connection();
        PreparedStatement ps=conn.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS)){
        ps.setString(1,"");    
        ps.setString(2,"");    
        ps.setString(3,"");    
        ps.setString(4,"");    
        ps.setString(5,"");    
        ps.setString(6,"");   
        ps.setString(7,"");  
        ps.setDate(8, java.sql.Date.valueOf("1900-01-01"));
        ps.setString(9,"Raul");
        int filas=ps.executeUpdate();
        if(filas>0){
            try(ResultSet rs=ps.getGeneratedKeys()){
                if(rs.next()){
                    int idGenerado=rs.getInt(1);
                    txtid.setText(String.valueOf(idGenerado));
                }
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "" + e.getMessage());
            }
    }
    
    }catch(SQLException e){
        JOptionPane.showMessageDialog(null, "" + e.getMessage());
    }  
    }
    
    public void buscar(int id,JTextField txtnombre,JTextField txtapellido,JTextField txtusuario,
            JPasswordField txtPass,JPasswordField txtConfirPass,JRadioButton rbSi,JRadioButton rbNo){

        String sql="SELECT * FROM usuarios WEHRE borrado!='*' and id=?"; 
        try(Connection conn=conexion.connection();
    PreparedStatement ps=conn.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS)){
            ps.setInt(1, id);
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                txtnombre.setText(rs.getString("nombre"));
                txtapellido.setText(rs.getString("apellido"));
                txtusuario.setText(rs.getString("usuario"));
                txtPass.setText(rs.getString("pass"));
                txtConfirPass.setText(rs.getString("confirpass"));
                String activo=rs.getString("estatus");
                if("A".equals(activo)){
                    rbSi.setSelected(true);
                    
                }else{
                    rbNo.setSelected(true);
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "no existe el registro");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "" + e.getMessage());
        }
    }
    
    /**
     * Creates new form CRUD_Calitos
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtusuario = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        txtConfirPass = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        btnnuevo = new javax.swing.JButton();
        btncambiar_contra = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();
        rbSi = new javax.swing.JRadioButton();
        rbNo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 67, 43, -1));

        jLabel2.setText("nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 113, 50, -1));

        jLabel3.setText("apellido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 163, 50, -1));

        jLabel4.setText("Nombre usuario");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 118, -1));

        jLabel5.setText("Registro Usuarios");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 15, 127, -1));

        jLabel6.setText("Contraseña");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        jLabel7.setText("Confirmar contraseña");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 150, -1));

        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidKeyReleased(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 62, 83, -1));
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 108, 83, -1));
        getContentPane().add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 158, 83, -1));

        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 150, -1));
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 140, -1));
        getContentPane().add(txtConfirPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 140, -1));

        jLabel8.setText("Activos");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 60, -1));

        btnnuevo.setText("nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        btncambiar_contra.setText("cambiar contraseña");
        getContentPane().add(btncambiar_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        btneditar.setText("Insertar");
        getContentPane().add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        btnborrar.setText("Borrar");
        getContentPane().add(btnborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        buttonGroup1.add(rbSi);
        rbSi.setText("Si");
        getContentPane().add(rbSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        buttonGroup1.add(rbNo);
        rbNo.setText("No");
        getContentPane().add(rbNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnguardarActionPerformed

    private void txtidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyReleased
        if(!txtid.getText().trim().isEmpty()){
            btnnuevo.setText("BUSCAR");
        }else{
            btnnuevo.setText("NUEVO");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidKeyReleased

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
       if(txtid.getText().trim().isEmpty()){
           insertar();
           btneditar.setEnabled(true);
           
       }else{
           int id=Integer.parseInt(txtid.getText());
           buscar(id, txtnombre, txtapellido, txtusuario, txtPass, txtConfirPass, rbSi, rbNo);
           btneditar.setEnabled(true);
           btnborrar.setEnabled(true);
       }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CRUD_Calitos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btncambiar_contra;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton rbNo;
    private javax.swing.JRadioButton rbSi;
    private javax.swing.JPasswordField txtConfirPass;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables

 
}
