/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.DAO;
import Entity.Entity;
import Factory.Factory;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author raulr
 */
public class GUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());
    
    Factory factory = new Factory();

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_id_producto = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JSpinner();
        btnSalir = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txt_testear = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("EXAMEN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 19, 71, -1));

        jLabel2.setText("id_producto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 79, -1, -1));

        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 116, 62, -1));

        jLabel4.setText("Precio");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 182, 62, -1));

        jLabel5.setText("Cantidad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 240, 62, -1));
        getContentPane().add(txt_id_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 74, 384, -1));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 124, 384, -1));
        getContentPane().add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 83, -1));
        getContentPane().add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 235, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 311, 87, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 100, -1));

        txt_testear.setText("Testear");
        txt_testear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_testearActionPerformed(evt);
            }
        });
        getContentPane().add(txt_testear, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 311, 87, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 109, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 191, 100, -1));

        btnInsertar.setText("Instertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 91, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
   
        try
        {
            int id = Integer.parseInt(this.txt_id_producto.getText());

            if(txt_id_producto == null)
            {
               JOptionPane.showMessageDialog(null, "Digite un ID.");
            }
            else
            {
                 Entity persona = factory.search(id);

                 if(persona.isItExists())
                 {
                     JOptionPane.showMessageDialog(null, "¡Datos encontrados!");
                     this.txt_nombre.setText(persona.getNombre());
                     this.txt_precio.setText(String.valueOf(persona.getPrecio()));
                     this.txt_cantidad.setValue(persona.getCantidad());
                 }
                 else
                 {
                     JOptionPane.showMessageDialog(null, "El registro no fue encontrado.");
                 }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Ocurrio un error: " + e.getMessage());
        }                                         

    // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
             
// TODO add your handling code here:
        this.dispose();   
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txt_testearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_testearActionPerformed
        // TODO add your handling code here:
        DAO dao = new DAO("examen_tabla");
    }//GEN-LAST:event_txt_testearActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
          try
        {
            int id =Integer.parseInt( this.txt_id_producto.getText());
            String nombre = this.txt_nombre.getText();
            double precio = Double.parseDouble(this.txt_precio.getText());
            int cantidad=Integer.parseInt(this.txt_cantidad.getValue().toString());
            
            Entity producto = new Entity(id, nombre,precio,cantidad);
            factory.insert(producto);
            JOptionPane.showMessageDialog(null, "¡Datos agregados!");
            //clear();
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Ocurrio un error: " + e.getMessage());
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
   try
        {
          int id = Integer.parseInt(this.txt_id_producto.getText());

            Entity productoBuscar = factory.search(id);

            if(productoBuscar.isItExists())
            {
                String nombre = this.txt_nombre.getText();
                double precio = Double.parseDouble(this.txt_precio.getText());
                int cantidad=Integer.parseInt(this.txt_cantidad.getValue().toString());
                int opcion = JOptionPane.showConfirmDialog(null, "¿Desea actualizar el registro?");

                if(opcion == 0)
                {
                    Entity personaActualizar = new Entity(id, nombre,precio,cantidad);
                    factory.update(personaActualizar);
                    JOptionPane.showMessageDialog(null, "¡Datos actualizados!");
                    
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "El registro no fue encontrado.");
                //clear();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Ocurrio un error: " + e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
  try
        {
            int id = Integer.parseInt(this.txt_id_producto.getText());
            Entity productoBuscar = factory.search(id);

            if(productoBuscar.isItExists())
            {
                int opcion = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el registro?");

                if(opcion == 0)
                {
                    factory.delete(id);
                    JOptionPane.showMessageDialog(null, "¡Datos eliminados!");
                   // clear();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "El registro no fue encontrado.");
               // clear();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Ocurrio un error: " + e.getMessage());
        }        
// TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner txt_cantidad;
    private javax.swing.JTextField txt_id_producto;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JButton txt_testear;
    // End of variables declaration//GEN-END:variables
}
