/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.DAO;
import Entity.Entity;
import Factory.Factory;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author raulr
 */
public class GUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());
    
    Factory factory = new Factory();

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_id_libro = new javax.swing.JTextField();
        txt_titulo = new javax.swing.JTextField();
        txt_autor = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txt_testear = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_edit = new javax.swing.JTextField();
        txt_anio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("EXAMEN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 19, 71, -1));

        jLabel2.setText("id_libro");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 79, -1, -1));

        jLabel3.setText("titulo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 116, 62, -1));

        jLabel4.setText("autor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 62, -1));
        getContentPane().add(txt_id_libro, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 74, 384, -1));
        getContentPane().add(txt_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 124, 384, -1));
        getContentPane().add(txt_autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 390, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 311, 87, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 100, -1));

        txt_testear.setText("Testear");
        txt_testear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_testearActionPerformed(evt);
            }
        });
        getContentPane().add(txt_testear, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 311, 87, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 109, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 191, 100, -1));

        btnInsertar.setText("Instertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 91, 100, -1));

        jLabel6.setText("editorial");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel7.setText("anio");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));
        getContentPane().add(txt_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 390, -1));
        getContentPane().add(txt_anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 390, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

//setId_libro
//setTitulo
//setAutor
//setEdit
//setAnio

//getId_libro
//getTitulo
//getAutor
//getEdit
//getAnio

//txt_id_lirbo
//txt_libro
//txt_autor
//txt_edit
//txt_anio
        try
        {
            int id = Integer.parseInt(this.txt_id_libro.getText());

            if(txt_id_libro == null)
            {
               JOptionPane.showMessageDialog(null, "Digite un ID.");
            }
            else
            {
                 Entity persona = factory.search(id);
//getId_libro
//getTitulo
//getAutor
//getEdit
//getAnio

//txt_id_lirbo
//txt_titulo
//txt_autor
//txt_edit
//txt_anio
                 if(persona.isItExists())
                 {
                     JOptionPane.showMessageDialog(null, "¡Datos encontrados!");
                      this.txt_titulo.setText(String.valueOf(persona.getTitulo()));
                     this.txt_autor.setText(String.valueOf(persona.getAutor()));
                     this.txt_edit.setText(String.valueOf(persona.getEdit()));
                     this.txt_anio.setText(String.valueOf(persona.getAnio()));
     

                 }
                 else
                 {
                     JOptionPane.showMessageDialog(null, "El registro no fue encontrado.");
                 }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Ocurrio un error: " + e.getMessage());
        }                                         

    // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
             
// TODO add your handling code here:
        this.dispose();   
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txt_testearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_testearActionPerformed
        // TODO add your handling code here:
        DAO dao = new DAO("examen_tabla2");
    }//GEN-LAST:event_txt_testearActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
    //getId_libro
//getTitulo
//getAutor
//getEdit
//getAnio

//txt_id_lirbo
//txt_titulo
//txt_autor
//txt_edit
//txt_anio      
        try
        {
            int id =Integer.parseInt( this.txt_id_libro.getText());
            String titulo = this.txt_titulo.getText();
            String autor = this.txt_autor.getText();
            String edit = this.txt_edit.getText();
            String anio = this.txt_anio.getText();
   
            
            Entity persona = new Entity(id, titulo,autor,edit,anio);
            factory.insert(persona);
            JOptionPane.showMessageDialog(null, "¡Datos agregados!");
            //clear();
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Ocurrio un error: " + e.getMessage());
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
   try
        {
          int id = Integer.parseInt(this.txt_id_libro.getText());

            Entity productoBuscar = factory.search(id);

            if(productoBuscar.isItExists())
            {
                String nombre = this.txt_titulo.getText();
                double precio = Double.parseDouble(this.txt_autor.getText());
                int cantidad=Integer.parseInt(this.txt_cantidad.getValue().toString());
                int opcion = JOptionPane.showConfirmDialog(null, "¿Desea actualizar el registro?");

                if(opcion == 0)
                {
                    Entity personaActualizar = new Entity(id, nombre,precio,cantidad);
                    factory.update(personaActualizar);
                    JOptionPane.showMessageDialog(null, "¡Datos actualizados!");
                    
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "El registro no fue encontrado.");
                //clear();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Ocurrio un error: " + e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
  try
        {
            int id = Integer.parseInt(this.txt_id_libro.getText());
            Entity productoBuscar = factory.search(id);

            if(productoBuscar.isItExists())
            {
                int opcion = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el registro?");

                if(opcion == 0)
                {
                    factory.delete(id);
                    JOptionPane.showMessageDialog(null, "¡Datos eliminados!");
                   // clear();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "El registro no fue encontrado.");
               // clear();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Ocurrio un error: " + e.getMessage());
        }        
// TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_anio;
    private javax.swing.JTextField txt_autor;
    private javax.swing.JTextField txt_edit;
    private javax.swing.JTextField txt_id_libro;
    private javax.swing.JButton txt_testear;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
